# setting which virtual environment its gonna run with
dist: trusty
sudo: false

# since angualar needs a browser to deploy its application
addons:
chrome: stable

languange: node_js
node_js: "8"

cache:
directories:
- ./node_modules

before_script:
- npm install -g --silent @angular/cli

# --prod for a production build
script:
- ng build --prod

notifications:
email:
on_failure: change
on_success: change